import { StyleSheet } from "react-native";

import { fonts } from "../../theme/typography";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  orb: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    opacity: 0.8,
  },
  orbTop: {
    top: -60,
    right: -90,
  },
  orbBottom: {
    bottom: 90,
    left: -80,
  },
  defaultLayout: {
    flex: 1,
    paddingHorizontal: 18,
    paddingBottom: 12,
  },
  defaultScroll: {
    flex: 1,
  },
  defaultLayoutContent: {
    paddingBottom: 28,
  },
  expandedLayout: {
    flex: 1,
    paddingHorizontal: 18,
    paddingBottom: 12,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    padding: 10,
    marginBottom: 28,
    overflow: "hidden",
    shadowOffset: { width: 0, height: 22 },
    shadowOpacity: 0.12,
    shadowRadius: 34,
    elevation: 10,
  },
  heroCardGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 180,
  },
  providerEmptyState: {
    borderRadius: 22,
    borderWidth: 1,
    minHeight: 96,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: "center",
    gap: 6,
  },
  providerEmptyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  providerEmptyBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  providerEmptyBadgeText: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  providerEmptyTitle: {
    fontSize: 14,
    fontFamily: fonts.display,
  },
  providerEmptyText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  eyebrow: {
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  livePill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  livePillText: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  stageBlock: {
    width: "100%",
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 22,
  },
  stageHalo: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    opacity: 0.18,
  },
  statusStrip: {
    width: "100%",
    maxWidth: 360,
    marginTop: 36,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 8,
  },
  statusStripCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  statusStripLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statusStripDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  statusStripTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontFamily: fonts.display,
  },
  statusStripDetail: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  statusStripInfoButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  transcriptShell: {
    height: 288,
    borderRadius: 32,
    borderWidth: 1,
    position: "relative",
    overflow: "hidden",
    paddingTop: 14,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 8,
  },
  expandedTranscriptDrawer: {
    flex: 1,
    borderRadius: 32,
    borderWidth: 1,
    position: "relative",
    paddingTop: 10,
    paddingHorizontal: 16,
    overflow: "hidden",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 8,
  },
  transcriptHeader: {
    paddingHorizontal: 16,
    paddingBottom: 8,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  transcriptBody: {
    flex: 1,
    minHeight: 0,
  },
  menuIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  expandButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  expandButtonText: {
    fontSize: 13,
    fontFamily: fonts.display,
  },
  previewTranscriptContent: {
    paddingTop: 4,
    paddingHorizontal: 16,
    paddingBottom: 26,
  },
  expandedTranscriptContent: {
    paddingBottom: 38,
  },
  expandedStageBar: {
    width: "100%",
    marginBottom: 12,
    zIndex: 1,
  },
  transcriptModal: {
    flex: 1,
  },
  statusDetailsOverlay: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  statusDetailsCard: {
    borderRadius: 30,
    borderWidth: 1,
    padding: 20,
    gap: 16,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 12,
  },
  statusDetailsHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  statusDetailsHeaderCopy: {
    flex: 1,
    gap: 6,
  },
  statusDetailsTitle: {
    fontSize: 24,
    lineHeight: 28,
    fontFamily: fonts.display,
  },
  statusDetailsSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  statusDetailsBadges: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
  },
  statusDetailsBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statusDetailsBadgeText: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  statusDetailsList: {
    gap: 10,
  },
  statusDetailsItem: {
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  statusDetailsItemLabel: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  expandedTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  modalTitle: {
    flex: 1,
    fontSize: 24,
    lineHeight: 28,
    fontFamily: fonts.display,
  },
  expandedTranscriptHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  },
  expandedTranscriptTitle: {
    flex: 1,
    fontSize: 18,
    lineHeight: 24,
    fontFamily: fonts.display,
  },
  expandedTranscriptHint: {
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 8,
    fontFamily: fonts.body,
  },
  usageSummaryCard: {
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    gap: 8,
  },
  usageSummaryHeader: {
    gap: 4,
  },
  usageSummaryTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontFamily: fonts.display,
  },
  usageSummaryMeta: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.mono,
  },
  usageSummaryNote: {
    fontSize: 12,
    lineHeight: 17,
    fontFamily: fonts.body,
  },
  usageSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  usageRouteList: {
    marginTop: 4,
    gap: 8,
  },
  usageRouteRow: {
    gap: 2,
  },
  usageRouteLabel: {
    fontSize: 12,
    lineHeight: 17,
    fontFamily: fonts.display,
  },
  usageRouteValue: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.mono,
  },
  usageSummaryMetric: {
    fontSize: 12,
    lineHeight: 17,
    fontFamily: fonts.mono,
  },
  usageSummaryMetricStrong: {
    fontSize: 12,
    lineHeight: 17,
    fontFamily: fonts.mono,
  },
});
