import { StyleSheet } from "react-native";

import { fonts } from "../../theme/typography";

export const styles = StyleSheet.create({
  container: { flex: 1, flexDirection: "row" },
  drawer: {
    width: "84%",
    maxWidth: 380,
    borderRightWidth: 1,
  },
  drawerGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 180,
  },
  backdrop: { flex: 1 },
  inlineActionOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 16,
    zIndex: 10,
  },
  inlineActionBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  actionSheet: {
    borderRadius: 28,
    borderWidth: 1,
    padding: 18,
    gap: 10,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 30,
    elevation: 10,
  },
  actionSheetTitle: {
    fontSize: 18,
    lineHeight: 22,
    fontFamily: fonts.display,
  },
  actionSheetMeta: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.body,
    marginBottom: 4,
  },
  actionSheetRow: {
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  actionSheetDeleteRow: {
    marginTop: 4,
  },
  actionSheetRowText: {
    fontSize: 14,
    fontFamily: fonts.display,
  },
  inlineRenameOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    paddingHorizontal: 20,
    zIndex: 12,
  },
  inlineRenameBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  renameCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 30,
    elevation: 10,
  },
  renameTitle: {
    fontSize: 20,
    lineHeight: 24,
    fontFamily: fonts.display,
  },
  renameHint: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  renameInput: {
    minHeight: 48,
    marginTop: 14,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: fonts.body,
  },
  renameActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 16,
  },
  renameAction: {
    minWidth: 92,
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  renameActionText: {
    fontSize: 13,
    fontFamily: fonts.display,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    paddingHorizontal: 18,
    paddingBottom: 16,
    borderBottomWidth: 1,
  },
  headerCopy: {
    flex: 1,
    gap: 5,
  },
  eyebrow: {
    fontSize: 11,
    letterSpacing: 1.1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  title: {
    fontSize: 26,
    lineHeight: 30,
    fontFamily: fonts.display,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.body,
  },
  closeButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  newSession: {
    marginTop: 16,
    marginHorizontal: 18,
    marginBottom: 14,
    borderRadius: 22,
    paddingVertical: 16,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 7,
  },
  newSessionText: {
    color: "#F4F8FF",
    fontSize: 15,
    fontFamily: fonts.display,
  },
  searchShell: {
    marginHorizontal: 18,
    marginBottom: 14,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    paddingLeft: 14,
    paddingRight: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchInput: {
    flex: 1,
    minHeight: 42,
    fontSize: 14,
    fontFamily: fonts.body,
  },
  searchClearButton: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  list: {
    paddingHorizontal: 18,
    paddingBottom: 24,
    gap: 10,
  },
  emptyState: {
    borderWidth: 1,
    borderRadius: 26,
    paddingHorizontal: 20,
    paddingVertical: 26,
    alignItems: "center",
    gap: 12,
    marginTop: 12,
  },
  emptyIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  emptyTitle: {
    fontSize: 18,
    textAlign: "center",
    fontFamily: fonts.display,
  },
  emptyDescription: {
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    fontFamily: fonts.body,
  },
  itemFrame: {
    borderRadius: 24,
    padding: 1.5,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 6,
    marginBottom: 10,
  },
  itemFrameInactive: {
    borderWidth: 1,
  },
  item: {
    position: "relative",
    borderRadius: 22.5,
    padding: 16,
    overflow: "hidden",
  },
  itemPressArea: {
    paddingRight: 44,
  },
  itemHeader: {
    marginBottom: 12,
  },
  itemTitleRow: {
    flex: 1,
    gap: 8,
  },
  itemTitle: {
    fontSize: 16,
    fontFamily: fonts.display,
  },
  itemMenuButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  itemMenuButtonFloating: {
    position: "absolute",
    top: 14,
    right: 14,
    zIndex: 2,
  },
  pinnedBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  pinnedBadgeText: {
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  itemMeta: {
    gap: 10,
  },
  itemMetaCopy: {
    gap: 10,
  },
  itemModelList: {
    gap: 8,
  },
  itemModelRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  itemModelIconWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  itemModelText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  itemStatsRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  itemStatChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  itemStatChipText: {
    fontSize: 11,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  itemTimelineRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
  },
  itemTimelineBlock: {
    flex: 1,
    gap: 4,
  },
  itemTimelineLabel: {
    fontSize: 11,
    letterSpacing: 0.7,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  itemTimelineValue: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  deleteAction: {
    width: 96,
    marginBottom: 10,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  deleteText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontFamily: fonts.display,
  },
});
