import { SettingsTab } from "./types";

export const TABS: SettingsTab[] = [
  "instructions",
  "providers",
  "stt",
  "tts",
  "ui",
];

export const SETTINGS_HEADER_TOP_PADDING = 22;
export const SETTINGS_HEADER_BOTTOM_PADDING = 18;
export const SETTINGS_HEADER_CONTROL_SIZE = 40;
export const SETTINGS_HEADER_HEIGHT =
  SETTINGS_HEADER_TOP_PADDING +
  SETTINGS_HEADER_BOTTOM_PADDING +
  SETTINGS_HEADER_CONTROL_SIZE;
export const SETTINGS_TAB_ROW_TOP_PADDING = 16;
export const SETTINGS_TAB_ROW_BOTTOM_PADDING = 14;
export const SETTINGS_TAB_BUTTON_HEIGHT = 38;
export const SETTINGS_TAB_SECTION_HEIGHT =
  SETTINGS_TAB_ROW_TOP_PADDING +
  SETTINGS_TAB_ROW_BOTTOM_PADDING +
  SETTINGS_TAB_BUTTON_HEIGHT;
export const SETTINGS_HERO_GLOW_HEIGHT =
  SETTINGS_HEADER_HEIGHT + SETTINGS_TAB_SECTION_HEIGHT;
