import { StyleSheet } from "react-native";

import { fonts } from "../../theme/typography";

import {
  SETTINGS_HEADER_BOTTOM_PADDING,
  SETTINGS_HEADER_CONTROL_SIZE,
  SETTINGS_HEADER_TOP_PADDING,
  SETTINGS_HERO_GLOW_HEIGHT,
  SETTINGS_TAB_BUTTON_HEIGHT,
  SETTINGS_TAB_ROW_BOTTOM_PADDING,
  SETTINGS_TAB_ROW_TOP_PADDING,
  SETTINGS_TAB_SECTION_HEIGHT,
} from "./constants";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  modal: {
    width: "100%",
    maxWidth: 460,
    flex: 1,
    borderRadius: 30,
    borderWidth: 1,
    overflow: "hidden",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.16,
    shadowRadius: 42,
    elevation: 12,
  },
  heroGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: SETTINGS_HERO_GLOW_HEIGHT,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingHorizontal: 22,
    paddingTop: SETTINGS_HEADER_TOP_PADDING,
    paddingBottom: SETTINGS_HEADER_BOTTOM_PADDING,
    borderBottomWidth: 1,
  },
  headerCopy: {
    flex: 1,
    gap: 6,
  },
  title: {
    fontSize: 28,
    lineHeight: 32,
    fontFamily: fonts.display,
  },
  closeButton: {
    width: SETTINGS_HEADER_CONTROL_SIZE,
    height: SETTINGS_HEADER_CONTROL_SIZE,
    borderRadius: SETTINGS_HEADER_CONTROL_SIZE / 2,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  tabRow: {
    paddingHorizontal: 18,
    paddingTop: SETTINGS_TAB_ROW_TOP_PADDING,
    paddingBottom: SETTINGS_TAB_ROW_BOTTOM_PADDING,
    gap: 10,
    alignItems: "center",
  },
  tabScroll: {
    flexGrow: 0,
    minHeight: SETTINGS_TAB_SECTION_HEIGHT,
  },
  tabButton: {
    minHeight: SETTINGS_TAB_BUTTON_HEIGHT,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonText: {
    fontSize: 13,
    fontFamily: fonts.display,
  },
  contentScroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 14,
  },
  tabIntroText: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
    marginBottom: 2,
  },
  sectionCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 16,
  },
  sectionLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.1,
    marginBottom: 12,
    fontFamily: fonts.mono,
  },
  sectionIntro: {
    fontSize: 12,
    lineHeight: 18,
    marginTop: -2,
    marginBottom: 14,
    fontFamily: fonts.body,
  },
  sectionHint: {
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
    fontFamily: fonts.body,
  },
  pricingSectionHint: {
    marginTop: 0,
    marginBottom: 12,
  },
  pricingAssumptionList: {
    gap: 10,
  },
  pricingAssumptionRow: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
    gap: 10,
  },
  pricingAssumptionCopy: {
    gap: 4,
  },
  pricingAssumptionTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.display,
  },
  pricingAssumptionMeta: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.mono,
  },
  pricingSourceButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  pricingSourceButtonText: {
    fontSize: 12,
    fontFamily: fonts.body,
  },
  responseModeList: {
    marginBottom: 14,
  },
  responseModeItem: {
    paddingBottom: 10,
    paddingTop: 14,
  },
  responseModeCopy: {
    gap: 4,
    marginBottom: 16,
  },
  responseModeTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontFamily: fonts.display,
  },
  responseModeDescription: {
    fontSize: 12,
    lineHeight: 17,
    fontFamily: fonts.body,
  },
  responseModePicker: {
    marginBottom: 10,
  },
  responseModePickerLast: {
    marginBottom: 0,
  },
  providerButtonGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  setupChecklistCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    marginBottom: 14,
  },
  setupChecklistHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  setupChecklistStatusPill: {
    marginTop: 0,
  },
  setupChecklistHint: {
    marginTop: 0,
  },
  setupChecklistList: {
    marginTop: 12,
    gap: 10,
  },
  setupChecklistItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  setupChecklistIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  setupChecklistCopy: {
    flex: 1,
    gap: 2,
  },
  setupChecklistLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  setupChecklistState: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  providerButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 4,
  },
  providerButtonBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  apiKeyCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  apiKeyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  apiKeyTitle: {
    fontSize: 14,
    fontFamily: fonts.display,
  },
  apiKeyPortalLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  apiKeyPortalLinkText: {
    fontSize: 12,
    fontFamily: fonts.display,
  },
  apiKeyHint: {
    marginTop: 6,
    marginBottom: 10,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  apiKeyInputRow: {
    position: "relative",
    justifyContent: "center",
  },
  apiKeyInput: {
    minHeight: 48,
    width: "100%",
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingRight: 54,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: fonts.body,
  },
  apiKeyVisibilityButton: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  apiKeyMetaRow: {
    marginTop: 10,
    minHeight: 18,
    justifyContent: "center",
  },
  apiKeyValidateLink: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  apiKeyValidateLinkDisabled: {
    opacity: 0.6,
  },
  apiKeyValidateText: {
    fontSize: 12,
    fontFamily: fonts.display,
  },
  validationCard: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  validationText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  promptCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    marginBottom: 14,
  },
  promptLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.1,
    marginBottom: 10,
    fontFamily: fonts.mono,
  },
  promptInput: {
    minHeight: 132,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    lineHeight: 22,
    textAlignVertical: "top",
    fontFamily: fonts.body,
  },
  previewCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
    marginTop: 8,
  },
  previewLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.1,
    marginBottom: 10,
    fontFamily: fonts.mono,
  },
  previewInput: {
    minHeight: 92,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    lineHeight: 22,
    textAlignVertical: "top",
    fontFamily: fonts.body,
  },
  previewHint: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  previewButton: {
    marginTop: 14,
    borderRadius: 18,
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 7,
  },
  previewButtonDisabled: {
    opacity: 0.55,
  },
  previewButtonBusy: {
    opacity: 0.82,
  },
  previewButtonText: {
    color: "#F4F8FF",
    fontSize: 14,
    fontFamily: fonts.display,
  },
  groupLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.1,
    marginBottom: 8,
    fontFamily: fonts.mono,
  },
  languageChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  languageChip: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  languageChipText: {
    fontSize: 13,
    fontFamily: fonts.display,
  },
  localPackCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    marginTop: 10,
  },
  previewLanguageBlock: {
    marginTop: 14,
    paddingTop: 14,
  },
  localPackHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  localPackCopy: {
    flex: 1,
  },
  localPackVoicePicker: {
    marginTop: 14,
  },
  localPackPreview: {
    marginTop: 14,
  },
  localPackButton: {
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  localPackButtonText: {
    color: "#F4F8FF",
    fontSize: 13,
    fontFamily: fonts.display,
  },
  speechDiagnosticHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  speechDiagnosticClear: {
    fontSize: 12,
    fontFamily: fonts.mono,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  radioRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
  },
  radioButtonWrap: {
    width: "50%",
    paddingHorizontal: 4,
    paddingBottom: 8,
  },
  radioButton: {
    minHeight: 50,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  radioButtonActive: {
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 7,
  },
  radioLabel: {
    fontSize: 14,
    textAlign: "center",
    fontFamily: fonts.display,
  },
  radioLabelActive: {
    color: "#F4F8FF",
  },
});
